version: 2.0
jobs:
  build:
    dockersize:
      machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS 
          
      - run: docker buid -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
   FROM alpine
   ENTERYPOINT echo "Hello World" 
     
