version: 2.0
jobs:
  build:
    dockerize:
      machine: true
      steps:
        - checkout
        #login to docker
        - run: docker login -u nabadoon -p Shadia12# 
        #Build the application image
        - run: docker buid -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
        #deploy the image
        - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
    
     
